apiVersion: v1
kind: Service
metadata:
  name: waitlist
  namespace: dev-05vws
  labels:
    app: waitlist
spec:
  type: ClusterIP
  selector:
    app: waitlist
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waitlist
  namespace: dev-05vws
  labels:
    app: waitlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waitlist
  template:
    metadata:
      labels:
        app: waitlist
    spec:
      containers:
        - name: waitlist-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 1000m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-docker-connect-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waitlist
  namespace: dev-05vws
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: waitlist-image-d2js.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: waitlist
                port:
                  number: 80
  tls:
    - hosts:
        - waitlist-image-d2js.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
