apiVersion: v1
kind: Service
metadata:
  name: Deploy1
  namespace: default
  labels:
    app: Deploy1
spec:
  type: ClusterIP
  selector:
    app: Deploy1
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deploy1
  namespace: default
  labels:
    app: Deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Deploy1
  template:
    metadata:
      labels:
        app: Deploy1
    spec:
      containers:
        - name: Deploy1-container
          image: satyamp07/waitlist:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 1000m
          env:
            - name: NEXT_PUBLIC_ATLAS_BACKEND
              value: https://api.atlas.scoutflo.com/api
      imagePullSecrets:
        - name: scoutflo-docker-connect-docker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Deploy1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: waitlist-image-clol8.scoutflo.agency
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: Deploy1
                port:
                  number: 80
  tls:
    - hosts:
        - waitlist-image-clol8.scoutflo.agency
      secretName: scoutflo-agency-wildcard-tls
